import globals from "globals";
import pluginJs from "@eslint/js";
import stylistic from '@stylistic/eslint-plugin';

export default [
	pluginJs.configs.recommended,
	{
    	languageOptions: {
    		globals: globals.nodeBuiltin
    	},
    },
    {
    	plugins: {
            '@stylistic': stylistic
        },
    	rules: {
    		
    		//"no-shadow": "warn",
    		
    		// "prefer-destructuring": "warn",
    		"prefer-destructuring": ["warn", {"object": true, "array": false}],
    		
    		//"prefer-template": "warn",
    		
    		//"complexity": ["warn", 25],
    		//"lines-between-class-members": "warn",
    		//"sort-imports": "warn",

			"guard-for-in": "warn",
    		"@stylistic/semi": "warn",
    		"array-bracket-spacing": "warn",
    		"arrow-parens": "warn",
    		"arrow-spacing": "warn",
    		"block-spacing": "warn",
			"comma-spacing": "warn",
			"comma-style": "warn",
			"computed-property-spacing": "warn",
			"dot-location": "warn",
			"eol-last": "warn",
			"@stylistic/function-call-spacing": "warn",
			"function-paren-newline": "warn",
			"generator-star-spacing": "warn",
			"implicit-arrow-linebreak": "warn",
			"key-spacing": "warn",
			"keyword-spacing": "warn",
			"linebreak-style": "warn",
			"max-len": ["warn", 100],
			"max-statements-per-line": ["warn", {"max": 2}],
			"new-parens": "warn",
			"no-confusing-arrow": "warn",
			"no-extra-semi": "warn",
			"no-floating-decimal": "warn",
			"no-mixed-operators": "warn",
			"no-mixed-spaces-and-tabs": "warn",
			"no-multi-spaces": "warn",
			"no-multiple-empty-lines": "warn",
			"no-trailing-spaces": "warn",
			"no-whitespace-before-property": "warn",
			"nonblock-statement-body-position": "warn",
			"object-curly-newline": "warn",
			"one-var-declaration-per-line": "warn",
			"operator-linebreak": "warn",
			"padding-line-between-statements": "warn",
			"quotes": ["warn", "single"],
			"rest-spread-spacing": "warn",
			"semi-spacing": "warn",
			"semi-style": "warn",
			"space-before-blocks": "warn",
			"space-before-function-paren": ["warn", {"anonymous": "always", "named": "never", "asyncArrow": "never"}],
			"space-in-parens": "warn",
			"space-infix-ops": "warn",
			"space-unary-ops": "warn",
			"spaced-comment": "warn",
			"switch-colon-spacing": "warn",
			"template-curly-spacing": "warn",
			"wrap-iife": "warn",
			"wrap-regex": "warn",
			"yield-star-spacing": "warn",
    		//
    		"array-callback-return": "warn",
    		"no-constructor-return": "warn",
    		"no-duplicate-imports": "warn",
    		"no-inner-declarations": "warn",
    		"no-promise-executor-return": "warn",
    		"no-self-compare": "warn",
    		"no-template-curly-in-string": "warn",
    		"no-unmodified-loop-condition": "warn",
    		"no-unreachable-loop": "warn",
    		"no-useless-assignment": "warn",
    		"require-atomic-updates": "warn",
    		"arrow-body-style": "warn",
    		"block-scoped-var": "warn",
    		"curly": "warn",
    		"default-case": "warn",
    		"default-case-last": "warn",
    		"default-param-last": "warn",
    		"dot-notation": "warn",
    		"eqeqeq": "warn",
    		"func-name-matching": "warn",
    		"func-style": ["warn", "declaration"],
    		"max-depth": "warn",
    		"max-nested-callbacks": "warn",
    		"no-alert": "warn",
    		"new-cap": "warn",
    		"no-array-constructor": "warn",
    		"no-caller": "warn",
			"no-div-regex": "warn",
			"no-empty-function": "warn",
			"no-eq-null": "warn",
			"no-eval": "warn",
			"no-extend-native": "warn",
			"no-extra-bind": "warn",
			"no-extra-label": "warn",
			"no-implicit-coercion": "warn",
			"no-implicit-globals": "warn",
			"no-implied-eval": "warn",
			"no-invalid-this": "warn",
			"no-iterator": "warn",
			"no-label-var": "warn",
			"no-labels": "warn",
			"no-lone-blocks": "warn",
			"no-lonely-if": "warn",
			"no-loop-func": "warn",
			"no-new": "warn",
			"no-new-func": "warn",
			"no-new-wrappers": "warn",
			"no-object-constructor": "warn",
			"no-param-reassign": "warn",
			"no-proto": "warn",
			"no-return-assign": "warn",
			"no-script-url": "warn",
			"no-sequences": "warn",
			"no-throw-literal": "warn",
			"no-undef-init": "warn",
			"no-unneeded-ternary": "warn",
			"no-unused-expressions": "warn",
			"no-useless-call": "warn",
			"no-useless-computed-key": "warn",
			"no-useless-concat": "warn",
			"no-useless-constructor": "warn",
			"no-useless-rename": "warn",
			"no-var": "warn",
			"no-void": "warn",
			"prefer-arrow-callback": "warn",
			"prefer-const": "warn",
			"prefer-exponentiation-operator": "warn",
			"prefer-numeric-literals": "warn",
			"prefer-object-has-own": "warn",
			"prefer-object-spread": "warn",
			"prefer-promise-reject-errors": "warn",
			"prefer-rest-params": "warn",
			"prefer-spread": "warn",
			"radix": "warn",
			"require-await": "warn",
			"strict": "warn",
			"symbol-description": "warn",
    	}
    },
	{
        ignores: ["*.config.*", ".misc/*", "lib/data/*"]
    },
];
